name: Merge and image push

on:
  push:
      branches: [ master ]
      # types: [ opened, synchronize, reopened ]

jobs:
  # Job 1: Runs on PRs and on direct merges to validate the codebase
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24' # Specify your Express app's Node version
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Test build
        run: npm run build

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ vars.DOCKER_USERNAME }}/notification-service:latest
            ${{ vars.DOCKER_USERNAME }}/notification-service:${{ github.sha }}
 
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Simulate CD Deployment
  #       run: |
  #         echo "PR successfully merged into ${{ github.ref_name }} branch."
  #         echo "Triggering deployment process for Express server..."
  #         # Insert your deployment script here (e.g., AWS, Render, Heroku, Docker)
