name: PR Validation

on:
  pull_request:
    branches: [ master ]
    # types: [ opened, synchronize, reopened ]
  
jobs:
  # Job 1: Runs on PRs and on direct merges to validate the codebase
  test-and-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24' # Specify your Express app's Node version
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Test build
        run: npm run build

      # - name: Run Linter (Optional but Recommended)
      #   run: npm run lint --if-present

      # - name: Run Tests
      #   run: npm test
